version: '3'

services:
  converter:
    container_name: converter
    build: .
    restart: always
    ports:
      - 9094:9094
    depends_on:
      - mongo
    environment:
      PORT: 9091
      MONGO_URI: mongodb://mongo/
      MONGO_DB: upload
      URL: /api/v1/
      URLBASE: 'http://localhost:'
      FORMATS_SUPPORTED_VIDEO: "['mov', 'm4a', '3gp', '3g2', 'mj2', 'mp4']"
      FORMATS_SUPPORTED_IMAGE: "['jpeg', 'png', 'jpg']"
      FORMATS_SUPPORTED_DOC: "['docx']"
    volumes:
      - converter_data:/app
    networks:
      - mongodbdev_infranet

volumes:
  converter_data:

networks:
  mongodbdev_infranet:
