version: '3'

services:
  converter:
    image: dilanof/converter-service:45
    container_name: converter
    restart: always
    ports:
      - 9094:9094
    environment:
      PORT: 9094
      MONGO_URI: mongodb://mongo/
      MONGO_DB: upload
      URL: /api/v1/
      URLBASE: 'http://localhost:'
      FORMATS_SUPPORTED_VIDEO: "['mov', 'm4a', '3gp', '3g2', 'mj2', 'mp4']"
      FORMATS_SUPPORTED_IMAGE: "['jpeg', 'png', 'jpg']"
      FORMATS_SUPPORTED_DOC: "['docx']"
    volumes:
      - converter_data:/app
    networks:
      - mongodbdev_infranet

volumes:
  converter_data:

networks:
  mongodbdev_infranet:
